(package "dummy-package"
         "0.1.0"
         "Dummy package test")

(package-file "dummy-package.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "26.1")
(depends-on "dash" "2.14")
(depends-on "seq")
(depends-on "f")
(depends-on "trinary")
(depends-on "lsp-mode")
