name: Activation CLI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        emacs-version:
          - 27.2
          - 28.2
          - snapshot
        include:
          - emacs-version: 'snapshot'
            allow_failure: true
    steps:
    - uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    # Remove expired DST Root CA X3 certificate. Workaround for
    # https://debbugs.gnu.org/cgi/bugreport.cgi?bug=51038 bug on Emacs 27.2.
    # https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-1126671598
    - name: Workaround for Emacs 27.2's Windows build from GNU FTP
      if: ${{ runner.os == 'Windows' && matrix.emacs-version == '27.2' }}
      run: |
        gci cert:\LocalMachine\Root\DAC9024F54D8F6DF94935FB1732638CA6AD77C13
        gci cert:\LocalMachine\Root\DAC9024F54D8F6DF94935FB1732638CA6AD77C13 | Remove-Item

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - uses: actions/checkout@v3
      
    - name: Grant execution permission
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: chmod -R 777 ./tests/fixtures/dummy-package/
      
    - name: Run tests
      shell: bash
      run: |
        ./tests/fixtures/dummy-package/run.sh
